/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidacaoFinanceiraRouteImport } from './routes/validacao-financeira'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as OperacoesRouteImport } from './routes/operacoes'
import { Route as NovidadesRouteImport } from './routes/novidades'
import { Route as LogsIntegracoesRouteImport } from './routes/logs-integracoes'
import { Route as LogsIaRouteImport } from './routes/logs-ia'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxFinanceiroRouteImport } from './routes/inbox-financeiro'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FluxosRouteImport } from './routes/fluxos'
import { Route as ExecutivoRouteImport } from './routes/executivo'
import { Route as ExcecoesRouteImport } from './routes/excecoes'
import { Route as ContasAReceberRouteImport } from './routes/contas-a-receber'
import { Route as ContasAPagarRouteImport } from './routes/contas-a-pagar'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConciliacaoRouteImport } from './routes/conciliacao'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CentralIaRouteImport } from './routes/central-ia'
import { Route as AutomacaoRouteImport } from './routes/automacao'
import { Route as AdvancedOpsRouteImport } from './routes/advanced-ops'
import { Route as IndexRouteImport } from './routes/index'

const ValidacaoFinanceiraRoute = ValidacaoFinanceiraRouteImport.update({
  id: '/validacao-financeira',
  path: '/validacao-financeira',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesRoute = OperacoesRouteImport.update({
  id: '/operacoes',
  path: '/operacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const NovidadesRoute = NovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIntegracoesRoute = LogsIntegracoesRouteImport.update({
  id: '/logs-integracoes',
  path: '/logs-integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIaRoute = LogsIaRouteImport.update({
  id: '/logs-ia',
  path: '/logs-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxFinanceiroRoute = InboxFinanceiroRouteImport.update({
  id: '/inbox-financeiro',
  path: '/inbox-financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxosRoute = FluxosRouteImport.update({
  id: '/fluxos',
  path: '/fluxos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutivoRoute = ExecutivoRouteImport.update({
  id: '/executivo',
  path: '/executivo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcecoesRoute = ExcecoesRouteImport.update({
  id: '/excecoes',
  path: '/excecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasAReceberRoute = ContasAReceberRouteImport.update({
  id: '/contas-a-receber',
  path: '/contas-a-receber',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasAPagarRoute = ContasAPagarRouteImport.update({
  id: '/contas-a-pagar',
  path: '/contas-a-pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacaoRoute = ConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralIaRoute = CentralIaRouteImport.update({
  id: '/central-ia',
  path: '/central-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacaoRoute = AutomacaoRouteImport.update({
  id: '/automacao',
  path: '/automacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedOpsRoute = AdvancedOpsRouteImport.update({
  id: '/advanced-ops',
  path: '/advanced-ops',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advanced-ops': typeof AdvancedOpsRoute
  '/automacao': typeof AutomacaoRoute
  '/central-ia': typeof CentralIaRoute
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/contas-a-receber': typeof ContasAReceberRoute
  '/excecoes': typeof ExcecoesRoute
  '/executivo': typeof ExecutivoRoute
  '/fluxos': typeof FluxosRoute
  '/fornecedores': typeof FornecedoresRoute
  '/inbox-financeiro': typeof InboxFinanceiroRoute
  '/login': typeof LoginRoute
  '/logs-ia': typeof LogsIaRoute
  '/logs-integracoes': typeof LogsIntegracoesRoute
  '/novidades': typeof NovidadesRoute
  '/operacoes': typeof OperacoesRoute
  '/relatorios': typeof RelatoriosRoute
  '/validacao-financeira': typeof ValidacaoFinanceiraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advanced-ops': typeof AdvancedOpsRoute
  '/automacao': typeof AutomacaoRoute
  '/central-ia': typeof CentralIaRoute
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/contas-a-receber': typeof ContasAReceberRoute
  '/excecoes': typeof ExcecoesRoute
  '/executivo': typeof ExecutivoRoute
  '/fluxos': typeof FluxosRoute
  '/fornecedores': typeof FornecedoresRoute
  '/inbox-financeiro': typeof InboxFinanceiroRoute
  '/login': typeof LoginRoute
  '/logs-ia': typeof LogsIaRoute
  '/logs-integracoes': typeof LogsIntegracoesRoute
  '/novidades': typeof NovidadesRoute
  '/operacoes': typeof OperacoesRoute
  '/relatorios': typeof RelatoriosRoute
  '/validacao-financeira': typeof ValidacaoFinanceiraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advanced-ops': typeof AdvancedOpsRoute
  '/automacao': typeof AutomacaoRoute
  '/central-ia': typeof CentralIaRoute
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/contas-a-receber': typeof ContasAReceberRoute
  '/excecoes': typeof ExcecoesRoute
  '/executivo': typeof ExecutivoRoute
  '/fluxos': typeof FluxosRoute
  '/fornecedores': typeof FornecedoresRoute
  '/inbox-financeiro': typeof InboxFinanceiroRoute
  '/login': typeof LoginRoute
  '/logs-ia': typeof LogsIaRoute
  '/logs-integracoes': typeof LogsIntegracoesRoute
  '/novidades': typeof NovidadesRoute
  '/operacoes': typeof OperacoesRoute
  '/relatorios': typeof RelatoriosRoute
  '/validacao-financeira': typeof ValidacaoFinanceiraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advanced-ops'
    | '/automacao'
    | '/central-ia'
    | '/chat'
    | '/clientes'
    | '/conciliacao'
    | '/configuracoes'
    | '/contas-a-pagar'
    | '/contas-a-receber'
    | '/excecoes'
    | '/executivo'
    | '/fluxos'
    | '/fornecedores'
    | '/inbox-financeiro'
    | '/login'
    | '/logs-ia'
    | '/logs-integracoes'
    | '/novidades'
    | '/operacoes'
    | '/relatorios'
    | '/validacao-financeira'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advanced-ops'
    | '/automacao'
    | '/central-ia'
    | '/chat'
    | '/clientes'
    | '/conciliacao'
    | '/configuracoes'
    | '/contas-a-pagar'
    | '/contas-a-receber'
    | '/excecoes'
    | '/executivo'
    | '/fluxos'
    | '/fornecedores'
    | '/inbox-financeiro'
    | '/login'
    | '/logs-ia'
    | '/logs-integracoes'
    | '/novidades'
    | '/operacoes'
    | '/relatorios'
    | '/validacao-financeira'
  id:
    | '__root__'
    | '/'
    | '/advanced-ops'
    | '/automacao'
    | '/central-ia'
    | '/chat'
    | '/clientes'
    | '/conciliacao'
    | '/configuracoes'
    | '/contas-a-pagar'
    | '/contas-a-receber'
    | '/excecoes'
    | '/executivo'
    | '/fluxos'
    | '/fornecedores'
    | '/inbox-financeiro'
    | '/login'
    | '/logs-ia'
    | '/logs-integracoes'
    | '/novidades'
    | '/operacoes'
    | '/relatorios'
    | '/validacao-financeira'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancedOpsRoute: typeof AdvancedOpsRoute
  AutomacaoRoute: typeof AutomacaoRoute
  CentralIaRoute: typeof CentralIaRoute
  ChatRoute: typeof ChatRoute
  ClientesRoute: typeof ClientesRoute
  ConciliacaoRoute: typeof ConciliacaoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContasAPagarRoute: typeof ContasAPagarRoute
  ContasAReceberRoute: typeof ContasAReceberRoute
  ExcecoesRoute: typeof ExcecoesRoute
  ExecutivoRoute: typeof ExecutivoRoute
  FluxosRoute: typeof FluxosRoute
  FornecedoresRoute: typeof FornecedoresRoute
  InboxFinanceiroRoute: typeof InboxFinanceiroRoute
  LoginRoute: typeof LoginRoute
  LogsIaRoute: typeof LogsIaRoute
  LogsIntegracoesRoute: typeof LogsIntegracoesRoute
  NovidadesRoute: typeof NovidadesRoute
  OperacoesRoute: typeof OperacoesRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ValidacaoFinanceiraRoute: typeof ValidacaoFinanceiraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validacao-financeira': {
      id: '/validacao-financeira'
      path: '/validacao-financeira'
      fullPath: '/validacao-financeira'
      preLoaderRoute: typeof ValidacaoFinanceiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes': {
      id: '/operacoes'
      path: '/operacoes'
      fullPath: '/operacoes'
      preLoaderRoute: typeof OperacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novidades': {
      id: '/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof NovidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs-integracoes': {
      id: '/logs-integracoes'
      path: '/logs-integracoes'
      fullPath: '/logs-integracoes'
      preLoaderRoute: typeof LogsIntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs-ia': {
      id: '/logs-ia'
      path: '/logs-ia'
      fullPath: '/logs-ia'
      preLoaderRoute: typeof LogsIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox-financeiro': {
      id: '/inbox-financeiro'
      path: '/inbox-financeiro'
      fullPath: '/inbox-financeiro'
      preLoaderRoute: typeof InboxFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxos': {
      id: '/fluxos'
      path: '/fluxos'
      fullPath: '/fluxos'
      preLoaderRoute: typeof FluxosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executivo': {
      id: '/executivo'
      path: '/executivo'
      fullPath: '/executivo'
      preLoaderRoute: typeof ExecutivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excecoes': {
      id: '/excecoes'
      path: '/excecoes'
      fullPath: '/excecoes'
      preLoaderRoute: typeof ExcecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas-a-receber': {
      id: '/contas-a-receber'
      path: '/contas-a-receber'
      fullPath: '/contas-a-receber'
      preLoaderRoute: typeof ContasAReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas-a-pagar': {
      id: '/contas-a-pagar'
      path: '/contas-a-pagar'
      fullPath: '/contas-a-pagar'
      preLoaderRoute: typeof ContasAPagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacao': {
      id: '/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof ConciliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-ia': {
      id: '/central-ia'
      path: '/central-ia'
      fullPath: '/central-ia'
      preLoaderRoute: typeof CentralIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacao': {
      id: '/automacao'
      path: '/automacao'
      fullPath: '/automacao'
      preLoaderRoute: typeof AutomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced-ops': {
      id: '/advanced-ops'
      path: '/advanced-ops'
      fullPath: '/advanced-ops'
      preLoaderRoute: typeof AdvancedOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancedOpsRoute: AdvancedOpsRoute,
  AutomacaoRoute: AutomacaoRoute,
  CentralIaRoute: CentralIaRoute,
  ChatRoute: ChatRoute,
  ClientesRoute: ClientesRoute,
  ConciliacaoRoute: ConciliacaoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContasAPagarRoute: ContasAPagarRoute,
  ContasAReceberRoute: ContasAReceberRoute,
  ExcecoesRoute: ExcecoesRoute,
  ExecutivoRoute: ExecutivoRoute,
  FluxosRoute: FluxosRoute,
  FornecedoresRoute: FornecedoresRoute,
  InboxFinanceiroRoute: InboxFinanceiroRoute,
  LoginRoute: LoginRoute,
  LogsIaRoute: LogsIaRoute,
  LogsIntegracoesRoute: LogsIntegracoesRoute,
  NovidadesRoute: NovidadesRoute,
  OperacoesRoute: OperacoesRoute,
  RelatoriosRoute: RelatoriosRoute,
  ValidacaoFinanceiraRoute: ValidacaoFinanceiraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
